version: '3.8'

services:
  db:
    image: postgres
    container_name: crud_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=joao0102
      - POSTGRES_DB=testedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: 